version: '3.9'
networks:
  shked-dev:
    driver: bridge
services:
  app:
    container_name: shked-auth-service
    build:
      context: .
      dockerfile: Sked-Authorization\Dockerfile
    ports:
      - '32764:100'
      - '32765:110'
    networks:
      - shked-dev
    restart: always
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:100/
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - shked-dev
volumes:
  mongo-db:

    
