openapi: 3.0.1
info:
  title: 'Shked-GroupsService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  '/API/Groups/{groupName}':
    get:
      tags:
        - Groups
      parameters:
        - name: groupName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ScheduleDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/ScheduleDTO'
components:
  schemas:
    DailySchedule:
      type: object
      properties:
        dates:
          type: array
          items:
            type: string
            format: date
          nullable: true
        classes:
          type: array
          items:
            $ref: '#/components/schemas/Lesson'
          nullable: true
        hashSum:
          type: string
          nullable: true
      additionalProperties: false
    Lesson:
      type: object
      properties:
        ordinal:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        lecturer:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
      additionalProperties: false
    ScheduleDTO:
      type: object
      properties:
        groupName:
          type: string
          nullable: true
        week:
          type: array
          items:
            $ref: '#/components/schemas/WeekdayDTO'
          nullable: true
      additionalProperties: false
    WeekdayDTO:
      type: object
      properties:
        daysSchedules:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DailySchedule'
          nullable: true
        dayNumber:
          type: integer
          format: int32
      additionalProperties: false