version: '3.9'
networks:
  shked-dev:
    driver: bridge
services:
  authservice:
    container_name: shked-auth-service
    image: wayne301/shked-authorizationservice:dev
    restart: always
    ports:
      - "100:100"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:100/
    networks:
      - shked-dev
  userservice:
    container_name: shked-user-service
    image: wayne301/shked-usersservice:dev
    restart: always
    depends_on: 
      - mongodb
    ports:
      - "110:110"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:110/
    networks:
      - shked-dev
  storageservice:
    container_name: shked-storage-service
    image: wayne301/shked-storageservice:dev
    restart: always
    ports:
      - "130:130"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:130/
    networks:
      - shked-dev
    extra_hosts:
      - "shked-tasks.host.docker.internal:host-gateway"
  groupservice:
    container_name: shked-group-service
    image: wayne301/shked-groupservice:dev
    depends_on: 
      - mongodb
    restart: always
    ports:
      - "120:120"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:120/
    networks:
      - shked-dev
  taskservice:
    container_name: shked-task-service
    image: wayne301/shked-taskservice:dev
    depends_on: 
      - mongodb
    restart: always
    ports:
      - "140:140"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://+:140/
    networks:
      - shked-dev
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - shked-dev
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: storage-api
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_DOMAIN: host.docker.internal
    command: server --console-address ":9001" /data
    container_name: minio      
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks: 
      - shked-dev
volumes:
  mongo-db:
  minio_storage:
